export const FETCH_ADDRESS_DATA = "FETCH_ADDRESS_DATA";
export const RECEIVE_ADDRESS_DATA = "RECEIVE_ADDRESS_DATA";
export const FETCH_ADDRESS_DATA_ERROR = "FETCH_ADDRESS_DATA_ERROR";

export const FETCH_VEHICLE_DATA = "FETCH_VEHICLE_DATA";
export const RECEIVE_VEHICLE_DATA = "RECEIVE_VEHICLE_DATA";
export const FETCH_VEHICLE_DATA_ERROR = "FETCH_VEHICLE_DATA_ERROR";